Repository KnightHacks/hackathon-2021-frontend, pull requests merged in 2021-10, with the labels that each got.

#69 Add country option.
  src/assets/content/countries.json
  src/pages/Register.js
  tailwind.config.js
Labels: mlh

#68 Convert School Name text field into dropdown
  package-lock.json
  package.json
  src/App.css
  src/assets/content/schools.json
  src/components/CustomMenuList.js
  src/pages/Register.js
Labels: enhancement, mlh

#81 Checkboxes
  package-lock.json
  package.json
  src/pages/Register.js
  tailwind.config.js
Labels: mlh

#79 Date of birth input
  package-lock.json
  package.json
  src/pages/Register.js
Labels: mlh

#91 Fixed dob when register
  src/pages/Register.js
Labels: bug
